# Generated by Django 4.0 on 2021-12-15 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phone_Driver', models.IntegerField()),
                ('Price', models.FloatField()),
                ('status_Car', models.CharField(max_length=15)),
                ('Fio_driver', models.CharField(max_length=30)),
                ('Car_mark', models.CharField(max_length=30)),
                ('people_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderSum', models.FloatField()),
                ('active_status', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=10)),
                ('role', models.CharField(default='user', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='zayavka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data_start_drive', models.DateField()),
                ('Start_point', models.CharField(max_length=45)),
                ('End_point', models.CharField(max_length=45)),
                ('Pozelanie', models.CharField(max_length=60)),
                ('people_num', models.IntegerField()),
                ('Cars_idCars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxtiapp.cars')),
                ('Users_idUsers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxtiapp.users')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_review', models.CharField(max_length=145)),
                ('Order_idOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxtiapp.orders')),
                ('user_iduser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxtiapp.users')),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='zayavka_idzayavka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxtiapp.zayavka'),
        ),
    ]
