# Generated by Django 4.0 on 2021-12-17 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxtiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='active_status',
            field=models.CharField(default='В процессе', max_length=30),
        ),
    ]
